### ISSUE TITLE
Please Add an Example

### ISSUE THREAD

**Issue by machineghost** [dmotz/express-spa-router#1]
This seems like exactly the library I'm looking for ... except I have no idea how to use it from the documentation.  For instance:

    app.use(require('express-spa-router')(app));

That's great, but then where do I tell Express SPA Router where my index route is?  Do I just create a router and add a route after I use Express SPA Router?

    var router = express.Router();
    router.get(`/`, function(req, res, next) {
        res.render('index', { title: 'Example' });
    });

... because that just gives me:

> browser.js:49 Warning: [react-router] Location "/" did not match any routes

A functional (or even a non-functional) example would really help explain things.

**Comment by dmotz** [comment]
All this library essentially does is reroute non-AJAX requests to `/`, so you only need to place it in the middleware stack above your server-side router.

It looks like your error is coming from an unrelated client-side router (react-router) that has no function bound to the `/` route.

**Comment by machineghost** [comment]
>It looks like your error is coming from an unrelated client-side router (react-router)

Heh, I missed the "react" part there and thought that was a message from the server.  I still think a basic example would be helpful though.
